### ISSUE TITLE
Notation

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/TransferEntropy.jl#62]
@Datseris For you book, what notation do you use for transfer entropy? In the docstrings, I'm using TE now, but this should perhaps be changed to comply with notation in the book if that differs.

**Comment by Datseris** [comment]
I'm still not entirely sold on a final notation. The original way of putting everything in a single equation was too much, so now we've split it into the following:

![image](https://user-images.githubusercontent.com/19669089/105365867-0397cc00-5bff-11eb-934b-7107ed0b588a.png)

What do you think?
